services:
  - type: web
    name: studymatena-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false          # You set this manually in Render dashboard
      - key: ADMIN_WA
        sync: false
      - key: FRONTEND_URL
        sync: false
